# session默认30min 设置为600s
server:
  session:
    timeout: 600
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  location: 127.0.0.1

# spring config
spring:
  application:
    name: project
#  profiles:
#    active: dev
#  devtools:
#    restart:
#      enabled: false
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
  data:
     mongodb:
        host: 120.79.89.98
        #username: caruser
        #password: normalneoway
        database: mnist_active_data
        port: 27017
        repositories: true
  mvc:
    static-path-pattern: /**

management:
  security:
    enabled : false
  context-path: /manage
#启用shutdown
endpoints:
  shutdown:
    enabled: true
#禁用密码验证
    sensitive: false

# logging config
logging:
  config: classpath:logback.xml

# 第三方接口获取access_token的对应密钥
mooctest:
  url: http://api.mooctest.net/
  secretKey: YWl0ZXN0OjQwMGFjMGI0ZjhkYTQwZDZhOThmMjk5MjVjOWRjZWIx

python_api:
  url: http:/127.0.0.1:8000/

base_path:
  image: E:\PyCharmProjects\keras_mnist\MNIST_data
  model: E:\PyCharmProjects\keras_mnist\new\del_models
  compose_image: E:temp